favourite-food: "пустота"
bow-name: "Лук-телепорт"
bow-description:
  - "Выстрели из лука"
  - "и телепортируйся"
teleported-message: "Вжухх!"
arrow-name: "Волшебная стрела игрока %playerName%"
arrow-description:
  - "Это твоя стрела"
  - "Куда она упадёт"
  - "Туда тебя перенесёт"
items:
  -
    material: APPLE
    price: 1
    count: 8
  -
    material: FURNACE
    price: 10
    count: 1